name: location_tracker_app
description: "Location tracking and route generation based mobile application."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_bloc: 9.0.0
  equatable: 2.0.7
  google_maps_flutter: 2.10.0
  flutter_polyline_points: 2.1.0
  get_it: 8.0.3
  geolocator: 13.0.2
  shared_preferences: 2.4.0
  haptic_feedback: 0.5.1+1
  geocoding: 3.0.0
  flutter_dotenv: 5.1.0

dependency_overrides:
  google_maps_flutter_ios: 2.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
